version: 2.1

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build puzzle pages
          command: cargo run
      - run:
          command: |
            mkdir -p puzzle_pages
            cp *.pdf puzzle_pages
      - store_artifacts:
          path: puzzle_pages

workflows:
  version: 2
  main:
    jobs:
      - build
